name: Build et Tests CI

on:
  push:
    branches: [ "main", "develop" ] # Déclenchement sur les branches principales
  pull_request:
    branches: [ "main" ] # Déclenchement lors d'une demande de fusion (Pull Request)

jobs:
  build:
    runs-on: ubuntu-latest # Exécute sur une machine Linux standard

    steps:
      - uses: actions/checkout@v4 # Étape 1 : Récupère le code du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # Utilise le cache Maven pour accélérer les builds

      - name: Build avec Maven et lancer les tests
        run: mvn -B package --file pom.xml # Exécute le build et les tests du projet multi-module